# Generated by Django 5.2.2 on 2026-02-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employeetask_leaverequest_profilechangerequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeetask',
            options={'ordering': ['-priority', 'status', 'due_date', '-created_at'], 'verbose_name': 'Задача сотрудника', 'verbose_name_plural': 'Задачи сотрудников'},
        ),
        migrations.AddField(
            model_name='employeetask',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий')], default=2, verbose_name='Приоритет'),
        ),
    ]
