# Generated by Django 5.2.2 on 2026-02-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_employeetask_options_employeetask_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telegram chat id'),
        ),
    ]
