# Generated by Django 5.2.2 on 2026-02-20 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile_telegram_chat_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpskillDirective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_zone', models.CharField(choices=[('Горячий цех', 'Горячий цех'), ('Холодный цех', 'Холодный цех'), ('Кондитерский участок', 'Кондитерский участок'), ('Фасовка', 'Фасовка')], max_length=64, verbose_name='Целевая зона')),
                ('target_level', models.CharField(choices=[('basic', 'Базовая'), ('middle', 'Средняя'), ('high', 'Высокая')], default='basic', max_length=20, verbose_name='Целевой уровень')),
                ('rationale', models.TextField(verbose_name='Обоснование необходимости')),
                ('status', models.CharField(choices=[('assigned', 'Назначено HR'), ('in_progress', 'В обучении'), ('employee_confirmed', 'Сотрудник подтвердил прохождение'), ('approved', 'Подтверждено HR'), ('rejected', 'Отклонено HR')], default='assigned', max_length=30, verbose_name='Статус')),
                ('planned_date', models.DateField(blank=True, null=True, verbose_name='Плановая дата')),
                ('employee_comment', models.TextField(blank=True, verbose_name='Комментарий сотрудника')),
                ('hr_comment', models.TextField(blank=True, verbose_name='Комментарий HR')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_upskill_directives', to=settings.AUTH_USER_MODEL, verbose_name='Назначил HR')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upskill_directives', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение на повышение квалификации',
                'verbose_name_plural': 'Назначения на повышение квалификации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeZoneAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('Горячий цех', 'Горячий цех'), ('Холодный цех', 'Холодный цех'), ('Кондитерский участок', 'Кондитерский участок'), ('Фасовка', 'Фасовка')], max_length=64, verbose_name='Зона/участок')),
                ('qualification_level', models.CharField(choices=[('basic', 'Базовая'), ('middle', 'Средняя'), ('high', 'Высокая')], max_length=20, verbose_name='Уровень квалификации')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдано')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_zone_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Кто выдал')),
            ],
            options={
                'verbose_name': 'Допуск к зоне',
                'verbose_name_plural': 'Допуски к зонам',
                'unique_together': {('employee', 'zone')},
            },
        ),
    ]
