# Generated by Django 5.2.2 on 2026-02-20 06:37

from django.db import migrations, models


def create_default_positions(apps, schema_editor):
    JobPosition = apps.get_model("core", "JobPosition")
    defaults = [
        ("Сотрудник производства", 10),
        ("Повар-универсал", 20),
        ("Кондитер", 30),
        ("Упаковщик", 40),
        ("Кладовщик", 50),
    ]
    for name, sort_order in defaults:
        JobPosition.objects.get_or_create(
            name=name,
            defaults={"sort_order": sort_order, "is_active": True},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_upskilldirective_employeezoneaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название должности')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('sort_order', models.PositiveSmallIntegerField(default=100, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Справочник должностей',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.RunPython(create_default_positions, migrations.RunPython.noop),
    ]
