# Generated by Django 5.2.2 on 2026-02-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_jobposition'),
    ]

    operations = [
        migrations.AddField(
            model_name='upskilldirective',
            name='employee_certificate',
            field=models.FileField(blank=True, null=True, upload_to='qualification_certificates/', verbose_name='Сертификат сотрудника'),
        ),
        migrations.AddField(
            model_name='upskilldirective',
            name='employee_certificate_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Сертификат загружен'),
        ),
    ]
