# Generated by Django 5.2.2 on 2026-02-16 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата смены')),
                ('start_time', models.TimeField(verbose_name='Начало')),
                ('end_time', models.TimeField(verbose_name='Окончание')),
                ('workshop', models.CharField(choices=[('Горячий цех', 'Горячий цех'), ('Холодный цех', 'Холодный цех'), ('Кондитерский участок', 'Кондитерский участок'), ('Фасовка', 'Фасовка')], max_length=64, verbose_name='Цех/участок')),
                ('planned_staff', models.PositiveSmallIntegerField(verbose_name='План сотрудников')),
                ('assigned_staff', models.PositiveSmallIntegerField(default=0, verbose_name='Назначено сотрудников')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_shifts', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный сотрудник')),
            ],
            options={
                'verbose_name': 'Смена',
                'verbose_name_plural': 'Смены',
                'ordering': ['date', 'start_time', 'workshop'],
            },
        ),
    ]
