# Generated by Django 5.2.2 on 2026-02-16 11:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255, verbose_name='Имя кандидата')),
                ('phone', models.CharField(max_length=32, verbose_name='Телефон')),
                ('interview_at', models.DateTimeField(verbose_name='Дата и время собеседования')),
                ('workshop', models.CharField(max_length=64, verbose_name='Цех/участок')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий HR')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('completed', 'Проведено'), ('pending_approval', 'На подтверждении у администратора'), ('rejected', 'Отклонено'), ('hired', 'Подтверждено')], default='scheduled', max_length=32, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_interviews', to=settings.AUTH_USER_MODEL, verbose_name='Подтвердил администратор')),
                ('employee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_origin', to=settings.AUTH_USER_MODEL, verbose_name='Созданный сотрудник')),
                ('hr_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hr_interviews', to=settings.AUTH_USER_MODEL, verbose_name='HR менеджер')),
            ],
            options={
                'verbose_name': 'Собеседование',
                'verbose_name_plural': 'Собеседования',
                'ordering': ['-interview_at', '-created_at'],
            },
        ),
    ]
