# Generated by Django 5.2.2 on 2026-02-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0002_interviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ознакомлен в'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='is_acknowledged',
            field=models.BooleanField(default=False, verbose_name='Сотрудник ознакомлен'),
        ),
    ]
