# Generated by Django 5.2.2 on 2026-02-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0003_shiftassignment_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewrequest',
            name='candidate_telegram_chat_id',
            field=models.CharField(blank=True, max_length=32, verbose_name='Telegram chat id кандидата'),
        ),
        migrations.CreateModel(
            name='InterviewTelegramInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Токен')),
                ('chat_id', models.CharField(blank=True, max_length=32, verbose_name='Telegram chat id')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Связано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_invite', to='hr_portal.interviewrequest', verbose_name='Собеседование')),
            ],
            options={
                'verbose_name': 'Telegram-приглашение кандидата',
                'verbose_name_plural': 'Telegram-приглашения кандидатов',
            },
        ),
    ]
