# Generated by Django 5.2.2 on 2026-02-20 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0004_interviewrequest_candidate_telegram_chat_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HiringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop', models.CharField(choices=[('Горячий цех', 'Горячий цех'), ('Холодный цех', 'Холодный цех'), ('Кондитерский участок', 'Кондитерский участок'), ('Фасовка', 'Фасовка')], max_length=64, verbose_name='\u0426\u0435\u0445/\u0443\u0447\u0430\u0441\u0442\u043e\u043a')),
                ('required_count', models.PositiveSmallIntegerField(default=1, verbose_name='\u0422\u0440\u0435\u0431\u0443\u0435\u0442\u0441\u044f \u0441\u043e\u0442\u0440\u0443\u0434\u043d\u0438\u043a\u043e\u0432')),
                ('reason', models.TextField(verbose_name='\u041e\u0431\u043e\u0441\u043d\u043e\u0432\u0430\u043d\u0438\u0435')),
                ('status', models.CharField(choices=[('open', '\u041e\u0442\u043a\u0440\u044b\u0442\u0430'), ('in_progress', '\u0412 \u0440\u0430\u0431\u043e\u0442\u0435 HR'), ('closed', '\u0417\u0430\u043a\u0440\u044b\u0442\u0430')], default='open', max_length=20, verbose_name='\u0421\u0442\u0430\u0442\u0443\u0441')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='\u041e\u0431\u043d\u043e\u0432\u043b\u0435\u043d\u043e')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043d\u043e')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hiring_requests', to=settings.AUTH_USER_MODEL, verbose_name='\u0421\u043e\u0437\u0434\u0430\u043b \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440')),
            ],
            options={
                'verbose_name': '\u0417\u0430\u044f\u0432\u043a\u0438 HR \u043d\u0430 \u043f\u043e\u0434\u0431\u043e\u0440',
                'verbose_name_plural': '\u0417\u0430\u044f\u0432\u043a\u0438 HR \u043d\u0430 \u043f\u043e\u0434\u0431\u043e\u0440',
                'ordering': ['status', '-created_at'],
            },
        ),
    ]
