# Generated by Django 5.2.2 on 2026-02-20 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_portal', '0005_hiringrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hiringrequest',
            options={'ordering': ['status', '-created_at'], 'verbose_name': 'Заявка HR на подбор', 'verbose_name_plural': 'Заявки HR на подбор'},
        ),
        migrations.AlterField(
            model_name='hiringrequest',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыто'),
        ),
    ]
