# Generated by Django 5.2.2 on 2026-02-03 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Создание'), ('update', 'Изменение'), ('lock', 'Блокировка'), ('unlock', 'Разблокировка'), ('login', 'Вход')], max_length=32, verbose_name='Действие')),
                ('object_type', models.CharField(max_length=64, verbose_name='Тип объекта')),
                ('object_id', models.CharField(max_length=64, verbose_name='ID объекта')),
                ('details', models.TextField(blank=True, verbose_name='Детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-created_at'],
            },
        ),
    ]
